Repository Davokadoh/ft_irc, pull requests merged in 2023-07, with the labels that each got.

#30 Add eval pdf
  EvalIRC_janv_2022_4.pdf
Labels: documentation

#31 Parser
  Makefile
  inc/Server.hpp
  src/Channel.cpp
  src/Client.cpp
  src/Server.cpp
  src/join.cpp
  src/names.cpp
  src/nick.cpp
  src/user.cpp
Labels: enhancement

#32 Fix previous merge
  ircserv
  src/Server.cpp
  src/nick.cpp
Labels: bug

#42 Getsource
  inc/Client.hpp
  src/Client.cpp
  src/Server.cpp
  src/nick.cpp
Labels: enhancement

#52 Fix reply to join
  inc/Macros.hpp
  src/join.cpp
  src/names.cpp
Labels: enhancement

#70 Cleaning fmt
  .clang-format
  inc/Channel.hpp
  inc/Client.hpp
  inc/Macros.hpp
  inc/Message.hpp
  inc/Msg.hpp
  inc/Server.hpp
  inc/parser.hpp
  src/Channel.cpp
  src/Client.cpp
  src/Message.cpp
  src/Server.cpp
  src/cap.cpp
  src/invite.cpp
  src/join.cpp
  src/kick.cpp
  src/main.cpp
  src/mode.cpp
  src/motd.cpp
  src/names.cpp
  src/nick.cpp
  src/notice.cpp
  src/part.cpp
  src/ping.cpp
  src/privmsg.cpp
  src/topic.cpp
  src/user.cpp
Labels: enhancement

#80 Channel across
  .clang-format
  inc/Channel.hpp
  inc/Client.hpp
  inc/Macros.hpp
  inc/Message.hpp
  inc/Msg.hpp
  inc/Server.hpp
  src/Channel.cpp
  src/Client.cpp
  src/Message.cpp
  src/Server.cpp
  src/cap.cpp
  src/cmds/nick.cpp
  src/cmds/privmsg.cpp
  src/cmds/user.cpp
  src/invite.cpp
  src/join.cpp
  src/kick.cpp
  src/main.cpp
  src/mode.cpp
  src/motd.cpp
  src/names.cpp
  src/nick.cpp
  src/notice.cpp
  src/part.cpp
  src/pass.cpp
  src/ping.cpp
  src/privmsg.cpp
  src/topic.cpp
  src/user.cpp
Labels: enhancement
